[2017-01-06 01:00:02] request.INFO: Matched route "app_api_eventslist_index". {"route":"app_api_eventslist_index","route_parameters":{"_controller":"controller.api.events_list:indexAction","_route":"app_api_eventslist_index"},"request_uri":"http://epictime.pl/api/web/events","method":"GET"} []
[2017-01-06 01:00:02] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-01-06 01:00:02] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-01-06 01:00:03] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[HY000] [1044] Access denied for user 'blizejswiata_4'@'%' to database 'epictime'" at /home/blizejswiata/ftp/epictime.pl/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1044] Access denied for user 'blizejswiata_4'@'%' to database 'epictime' at /home/blizejswiata/ftp/epictime.pl/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'blizejswiata_4'@'%' to database 'epictime' at /home/blizejswiata/ftp/epictime.pl/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'blizejswiata_4'@'%' to database 'epictime' at /home/blizejswiata/ftp/epictime.pl/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-01-06 01:00:03] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-01-06 01:00:11] request.INFO: Matched route "app_api_eventgroupslist_index". {"route":"app_api_eventgroupslist_index","route_parameters":{"_controller":"controller.api.event_groups_list:indexAction","_route":"app_api_eventgroupslist_index"},"request_uri":"http://epictime.pl/api/web/eventGroups","method":"GET"} []
[2017-01-06 01:00:11] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-01-06 01:00:11] security.DEBUG: User was reloaded from a user provider. {"username":"admin","provider":"Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider"} []
[2017-01-06 01:00:11] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\ConnectionException: "An exception occured in driver: SQLSTATE[HY000] [1044] Access denied for user 'blizejswiata_4'@'%' to database 'epictime'" at /home/blizejswiata/ftp/epictime.pl/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 103 {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1044] Access denied for user 'blizejswiata_4'@'%' to database 'epictime' at /home/blizejswiata/ftp/epictime.pl/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'blizejswiata_4'@'%' to database 'epictime' at /home/blizejswiata/ftp/epictime.pl/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1044): SQLSTATE[HY000] [1044] Access denied for user 'blizejswiata_4'@'%' to database 'epictime' at /home/blizejswiata/ftp/epictime.pl/api/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
[2017-01-06 01:00:11] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
